version: '3.1'

services:
  app:
    container_name: face_detection_app_1
    ports:
      - "8005:8005"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    env_file:
      - .env

networks:
  common:
    external: true