version: '3.1'

services:
  nginx:
    ports:
      - "80:80"
    build:
      context: ./etc/nginx/
      dockerfile: Dockerfile
    depends_on:
      - app

  app:
    ports:
      - "8005:8005"
    build:
      context: .
      dockerfile: Dockerfile